### ISSUE TITLE
random policy is not working for a sampled efficient zero env with continuous actions

### ISSUE THREAD

**Issue by duxtinto** [opendilab/LightZero#117]
# How to reproduce it?

1. add `random_collect_episode_num=10` to the some continuous env (e.g. lunarlander_cont_sampled_efficientzero_config.py)

![image](https://github.com/opendilab/LightZero/assets/333268/e0730fc4-fd15-4b66-967c-5680e9516e78)

# What's happening?

I'm getting the next error on this line:

![image](https://github.com/opendilab/LightZero/assets/333268/fad53559-122a-4ed6-973d-203d65944827)

![image](https://github.com/opendilab/LightZero/assets/333268/93791bac-6c03-4ab5-892c-b6474df5078f)

**Comment by puyuan1996** [comment]
Hello,

We have upgraded our `random_policy` to now support continuous action spaces. This enhancement has been detailed in our latest [PR118](https://github.com/opendilab/LightZero/pull/118), which you are welcome to review. 

However, it's worth emphasizing that in the training environment using the Sampled EfficientZero algorithm and continuous action spaces, since the SEZ agent fundamentally samples actions from a stochastic policy, the addition of random episodes in the early stages may not significantly impact performance optimization.

Feel free to raise any questions or discussions. Best wishes.

**Comment by duxtinto** [comment]
Hi @puyuan1996 ! Nice to meet you!

Thank you very much for your quick solution, and for your explanation about why the addition of random episodes at the beginning should not impact the performance of the SEZ algorithm :+1: 

> This enhancement has been detailed in our latest https://github.com/opendilab/LightZero/pull/118, which you are welcome to review.

thank you very much, but I don't think that I have enough knowledge to review the solution on that PR :sweat_smile: 

Best regards,

David.
