### ISSUE TITLE
Pip install failing on linux

### ISSUE THREAD

**Issue by Natithan** [opendilab/LightZero#140]
Hi,

I'm getting the following error when following the installation instruction:
```
Collecting pygame==2.1.0 (from gym==0.25.1->gym[accept-rom-license]==0.25.1->LightZero==0.0.2)
  Using cached pygame-2.1.0.tar.gz (5.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using UNIX configuration...

      /bin/sh: 1: sdl2-config: not found
      /bin/sh: 1: sdl2-config: not found
      /bin/sh: 1: sdl2-config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jku32nqq/pygame_c061e2c456b84204bbc5fc7abc1e8f5c/setup.py", line 388, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "/tmp/pip-install-jku32nqq/pygame_c061e2c456b84204bbc5fc7abc1e8f5c/buildconfig/config.py", line 234, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-jku32nqq/pygame_c061e2c456b84204bbc5fc7abc1e8f5c/buildconfig/config_unix.py", line 188, in main
          DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-jku32nqq/pygame_c061e2c456b84204bbc5fc7abc1e8f5c/buildconfig/config_unix.py", line 39, in __init__
          self.ver = config[0].strip()
                     ~~~~~~^^^
      IndexError: list index out of range

      Hunting dependencies...

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/Compilation
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```
My linux details are:
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
Any idea how to solve this? 

As alternative I also tried just downloading the source code and running it, but that gives me some problem with importing ``ez_tree`` in ``lzero/mcts/tree_search/mcts_ctree.py``. Trying to fix that by adding ``import pyximport; pyximport.install()`` following [this](https://stackoverflow.com/questions/7508803/how-do-i-import-function-from-pyx-file-in-python) then leads to a compile error.

Thanks in advance!

**Comment by puyuan1996** [comment]
Hello,

This issue is occurring while trying to install pygame version 2.1.0, which requires the sdl2 library. From the error log, it appears that sdl2-config can't be found in your system, suggesting that the SDL2 library is either not installed or not properly installed.

You can try the following steps to resolve this issue:

1. If you're on a Linux system, you can install sdl2 via your package manager. For example, on Ubuntu you can use the following command:

```bash
sudo apt-get install libsdl2-dev
```

2. If you're on macOS, you can install sdl2 using Homebrew:

```bash
brew install sdl2
```

3. After installation, try installing pygame again. If you still encounter issues, you might need to check whether SDL2 has been added to your system path.

4. If the issue persists, you could consider using a different version of pygame, or using a Python distribution that already includes all dependencies, such as Anaconda.

Please note that you may need appropriate system permissions to perform these steps. If you encounter difficulties executing these steps, you may need to seek more specific technical support. 

Note part of this suggestion is provided by GPT-4 :)

 Best wishes.
