### ISSUE TITLE
gomoku muzero self play train problem

### ISSUE THREAD

**Issue by wx5223** [opendilab/LightZero#169]
when try the demo file gomoku_muzero_sp_mode_config.py , the model seem can't study any knowledge, even i increase the max_env_step try to train longer.
i just use the default params, maybe something wrong in my usage? or the self play training ?  

any help will be appreciated~

![1](https://github.com/opendilab/LightZero/assets/3054889/3a3bdf0d-94f0-4aa8-94b8-ac8e2c04917f)
![screenshot-20231219-191735](https://github.com/opendilab/LightZero/assets/3054889/6a52bf9d-a86d-4769-a01c-7dc299bc075e)
![screenshot-20231219-191610](https://github.com/opendilab/LightZero/assets/3054889/05f30b6c-cbe2-455b-98db-e7f13ab32ec2)
![screenshot-20231219-191759](https://github.com/opendilab/LightZero/assets/3054889/96bb380f-87e1-4d32-9481-158943d524d3)

**Comment by puyuan1996** [comment]
- Hello, in our previous experiments, we found that under the default settings, the Gomoku MuZero in[ self_play_mode](https://github.com/opendilab/LightZero/blob/main/zoo/board_games/gomoku/config/gomoku_muzero_sp_mode_config.py)  requires training of over 500K environmental steps in order to observe assessment rewards consistently exceeding zero, indicating that all evaluation games result in wins or draws for the agent. To achieve superior performance, it is advisable to increase the `num_simulations` parameter to a higher value, such as 100, during evaluation. 

- In fact，our previous experiments and analyses were primarily focused on testing in [play_with_bot_mode](https://github.com/opendilab/LightZero/blob/main/zoo/board_games/gomoku/config/gomoku_muzero_bot_mode_config.py), and we **did not** meticulously adjust the parameters for the self-play training mode. Therefore, to attain more stable and efficient performance, it is recommended to conduct a thorough analysis of the current training conditions and make appropriate adjustments based on the findings. We appreciate your feedback and look forward to further communication to optimize the training process.
