### ISSUE TITLE
Question about gumbel_scale and dirichlet noise in Gumbel MuZero

### ISSUE THREAD

**Issue by sbl1996** [opendilab/LightZero#174]
I notice that your implementation of Gumbel MuZero has two differences with the original algorithm.

1. The gumbel_scale is fixed to 10.0, while mctx uses 1.0 or 0.0 (only in evaluation).
2. Dirichlet noises are used in the root node, the same as MuZero, while the paper says "Gumbel MuZero does not use Dirichlet noise" to ensure policy improvement.

I guess that you use these two approaches to encourage exploration during training. Could you share your insights or experimental results for these two differences? Thank you very much!

**Comment by puyuan1996** [comment]
- Hello, thank you for your question. Apologies for the late reply. In our implementation, we opted to use a `scale` of 10 for the Gumbel distribution instead of 1 since our early experiments indicated that this enhances exploratory behavior. As for the testing of other parameters, we plan to delve further into these in our future experiments. 
- The addition of `Dirichlet noise` to the root node was an oversight in our implementation, but intuitively, we believe it only increases the level of exploration at the root node and is unlikely to have a negative impact on performance. We will also provide results from experiments conducted without this noise in our subsequent experiments. 
- Thank you for your patience.
