### ISSUE TITLE
the sampled efficient zero portion of the code

### ISSUE THREAD

**Issue by LiuDongyang39** [opendilab/LightZero#218]
Hello，I was wondering if the sampled efficient zero portion of the code didn't use the empirical distribution from the original sampledmuzero paper to generate the prior probability of the child nodes?

**Comment by puyuan1996** [comment]
Hello, we have implemented based on the empirical distribution in the SampledMuZero original paper as priors for Child Nodes. You can refer to our code in ptree and ctree (located at [ptree](https://github.com/opendilab/LightZero/blob/main/lzero/mcts/ptree/ptree_sez.py#L607) and [ctree](https://github.com/opendilab/LightZero/blob/main/lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp#L1062) respectively). Additionally, based on the discussions in this [issue](https://github.com/opendilab/LightZero/issues/210), we plan to perform some upcoming optimizations on the performance of sampled_efficientzero. Thank you for your patience and support.

**Comment by puyuan1996** [comment]
Hello! We have implemented functionalities related to the empirical distribution as described in the original SampledMuZero paper. You can refer to our [ptree](https://github.com/opendilab/LightZero/blob/main/lzero/mcts/ptree/ptree_sez.py#L607) and [ctree](https://github.com/opendilab/LightZero/blob/main/lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp#L1062) codes for specific implementation details. Please note that since the K actions we sample are non-repetitive, the empirical distribution is essentially a re-normalization of the original probabilities (for discrete action spaces) or log probabilities (for continuous action spaces). As the original author's code is not open source, this implementation is based solely on our understanding. Additionally, following recent discussions on this [issue](https://github.com/opendilab/LightZero/issues/210), we plan to optimize the performance of sampled_efficientzero soon. Thank you for your patience and support.

**Comment by LiuDongyang39** [comment]
Thank you very much for your detailed response and for sharing the specifics of the implementation. I appreciate the efforts you and your team are putting into the development of the SampledMuZero functionalities.  Understanding that this implementation was crafted from the ground up, given the absence of open-source code from the original authors, I can certainly appreciate the complexity and innovation involved in your approach. I am also looking forward to the upcoming optimizations to the sampled_efficientzero algorithm.  Please keep me updated on any new developments or insights that might arise as you continue to refine the implementation.









At 2024-04-18 12:03:32, "蒲源" ***@***.***> wrote:

Hello! We have implemented functionalities related to the empirical distribution as described in the original SampledMuZero paper. You can refer to our ptree and ctree codes for specific implementation details. Please note that since the K actions we sample are non-repetitive, the empirical distribution is essentially a re-normalization of the original probabilities (for discrete action spaces) or log probabilities (for continuous action spaces). As the original author's code is not open source, this implementation is based solely on our understanding. Additionally, following recent discussions on this issue, we plan to optimize the performance of sampled_efficientzero soon. Thank you for your patience and support.
