### ISSUE TITLE
[bugs] bugs when run basic algorithms and envs 

### ISSUE THREAD

**Issue by walkacross** [opendilab/LightZero#302]
hi @puyuan1996 ,  Thanks for continuously open-sourcing algorithms related to MuZero.

A small suggestion: if the basic code doesn't run smoothly, it might make newcomers feel a bit frustrated.

# 0 how to install
~~~
conda create -n lightzero python=3.8

git clone https://github.com/opendilab/LightZero.git
cd LightZero
pip3 install -e .
~~~

# 1 Envs Errors

## 1.1 LunarLander errors

~~~
python lunarlander_disc_muzero_config.py
~~~

### LunarLander version error
1. gymnasium.error.DeprecatedEnv: Environment version v2 for `LunarLander` is deprecated. Please use `LunarLander-v3` instead.
2. when modify the config to LunarLander-v3, new error occurs
~~~
   low=self._env.reward_range[0], high=self._env.reward_range[1], shape=(1,), dtype=np.float32
AttributeError: 'TimeLimit' object has no attribute 'reward_range'
~~~
### suggestions
* fix the version of Gymnasium requirements.txt if necessary, p.s. [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) has released the v1.0.0

## 1.2 2048-game render error

* it works when set the render_mode="image_savefile_mode"
* it doesn't render when set the ender_mode="image_realtime_mode"
~~~
import numpy as np
import pytest
from easydict import EasyDict

from game_2048_env import Game2048Env

cfg = Game2048Env.default_config()
print(cfg)
env = Game2048Env(cfg=cfg)

obs = env.reset()

for i in range(10000):
    #env.render(mode="image_realtime_mode")
    
    action = np.random.choice([0,1,2,3])
    obs, reward, done, info = env.step(action)
~~~

# 1.3 cartpole envs import error
when eval the pretrained model
~~~
python cartpole_eval.py
~~~

os library not imported in [cartpole envs](https://github.com/opendilab/LightZero/blob/main/zoo/classic_control/cartpole/envs/cartpole_lightzero_env.py)
~~~
    def save_gif_replay(self) -> None:
        """
        Save the recorded frames as a GIF replay.
        """
        if not os.path.exists(self._replay_path_gif):
            os.makedirs(self._replay_path_gif)
        gif_path = os.path.join(self._replay_path_gif, gif_filename)
~~~

# 2 algorithms error
## 2.1 bugs in stochastic-muzero when run game-2048 

~~~
python stochastic_muzero_2048_config.py
~~~

error seems happen when learner save ckpt
~~~
    batch_rewards = np.asarray(batch_rewards)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (512, 6) + inhomogeneous part.
Exception ignored in: <function MuZeroCollector.__del__ at 0x7eb1535758b0>
Traceback (most recent call last):
LightZero/lzero/worker/muzero_collector.py", line 196, in __del__
    self.close()
LightZero/lzero/worker/muzero_collector.py", line 185, in close
    self._env.close()
 /anaconda3/envs/lightzero/lib/python3.8/site-packages/ding/envs/env_manager/subprocess_env_manager.py", line 635, in close
    p.send(['close', None, None])
  envs/lightzero/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  /anaconda3/envs/lightzero/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  /anaconda3/envs/lightzero/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
~~~
CI/CD(github actions ) matters, but it doesn't seem to be serving its intended purpose in this repository.

**Comment by puyuan1996** [comment]
Hello, thank you very much for your feedback and suggestions!

Regarding the **LunarLander version error**, we have resolved the issue by modifying the version requirements for **gymnasium** and **numpy** in the `requirements.txt` file. Currently, the `lunarlander_disc_muzero_config.py` can run successfully. In the future, we plan to adapt it to the latest version of Gymnasium.

As for the **2048-game render error**, all tests in `zoo/game_2048/envs/test_game_2048_env.py` have passed, indicating that `mode="image_realtime_mode"` can render properly on the screen.

Regarding the **cartpole envs import error** and the **reward type bug in game-204**, these issues have been fixed in this PR (https://github.com/opendilab/LightZero/pull/304). Previously, these problems arose due to the failure to properly adapt the environments during code updates. Moving forward, we will further improve the code refactoring and validation processes to ensure smoothness and stability.

Finally, thank you again for submitting these bug reports! If you have any further questions or suggestions, please feel free to reach out. We greatly appreciate your contributions!
