### ISSUE TITLE
requirement torch<=1.12.1,>=1.1.0 (from di-engine[common-env]) (from versions: 2.0.0, 2.0.1)

### ISSUE THREAD

**Issue by tommybell0** [opendilab/LightZero#58]
INFO: pip is looking at multiple versions of di-engine[common-env] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch<=1.12.1,>=1.1.0 (from di-engine[common-env]) (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch<=1.12.1,>=1.1.0

**Comment by puyuan1996** [comment]
Hello,

You may be able to install pytorch directly through a command similar to the following to see if it succeeds：
```
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```
If you encounter similar errors, they may be caused by the following reasons:
1. Python Version Incompatibility: PyTorch versions from 1.1.0 to 1.12.1 may not support your current Python version. You could try switching to another Python version (for example, Python 3.8), and then try again.
2. PyPI Source Issue: The PyPI source you are using may not have these PyTorch versions. You could try switching to another PyPI source, for example, using Tsinghua University's PyPI source.

If you still can't install it successfully, to better assist you, could you please provide more information related to your operating system, Python version, and DI-engine version?

Best regards.
