### ISSUE TITLE
A few questions about starting out and the Chess environment?

### ISSUE THREAD

**Issue by lcmaier** [opendilab/LightZero#69]
I'm very interested in using LightZero's chess environment to train some RL chess agents--however, I'm running into a few issues just setting it up. I've installed the module correctly (I think), and have the following initial code:
```
from LightZero.zoo.board_games.chess.envs.chess_env import ChessEnv
from LightZero.lzero.envs.wrappers.lightzero_env_wrapper import LightZeroEnvWrapper
from telnetlib import Telnet # This is just to silence a warning thrown when I don't have this line in here

env = ChessEnv()
lzero_env = LightZeroEnvWrapper(env, {'is_train': True})
```

This code throws an AssertionError, specifically:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 2
      1 env = ChessEnv()
----> 2 lzero_env = LightZeroEnvWrapper(env, {'is_train': True})

File [e:\000_work\ChessAI\LightZero\lzero\envs\wrappers\lightzero_env_wrapper.py:31](file:///E:/000_work/ChessAI/LightZero/lzero/envs/wrappers/lightzero_env_wrapper.py:31), in LightZeroEnvWrapper.__init__(self, env, cfg)
     29 super().__init__(env)
     30 assert 'is_train' in cfg, '`is_train` flag must set in the config of env'
---> 31 self.is_train = cfg.is_train
     32 self.cfg = cfg
     33 self.env_name = cfg.env_name

AttributeError: 'dict' object has no attribute 'is_train'
```
I set `cfg` to a dictionary because initially when I ran it with no positional argument (or None) for the cfg, I get the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 2
      1 env = ChessEnv()
----> 2 lzero_env = LightZeroEnvWrapper(env, None)

File [e:\000_work\ChessAI\LightZero\lzero\envs\wrappers\lightzero_env_wrapper.py:30](file:///E:/000_work/ChessAI/LightZero/lzero/envs/wrappers/lightzero_env_wrapper.py:30), in LightZeroEnvWrapper.__init__(self, env, cfg)
     22 """
     23 Overview:
     24     Initialize ``self.`` See ``help(type(self))`` for accurate signature;  \
   (...)
     27     - env (:obj:`gym.Env`): the environment to wrap.
     28 """
     29 super().__init__(env)
---> 30 assert 'is_train' in cfg, '`is_train` flag must set in the config of env'
     31 self.is_train = cfg.is_train
     32 self.cfg = cfg

TypeError: argument of type 'NoneType' is not iterable
```
What is `cfg` supposed to be, class or iterable (or both somehow)? I can't find much in the source code. In addition, there seem to be parts of the chess environment itself that are WIP (ie the `chess_alphazero_sp-mode_config.py` file in the chess config folder)--should I be cognizant of that when I'm writing my MCTS RL agents? Thanks in advance

**Comment by lcmaier** [comment]
Thank you so much for the detailed response. I've spent most of today digging around in the files you suggested, and I have a quick follow-up question: what needs to be in an environment configuration dictionary? I'm having trouble parsing the parts of the tictactoe config file that I should borrow and which parts to discard (if any?). For example, the env dict for tictactoe has an attribute called `battle_mode`, which I'm assuming I can drop for the chess env, but I'm not 100% sure due to not knowing exactly what should be there.

**Comment by puyuan1996** [comment]
- The `battle_mode` is a setting used in AlphaZero training that determines how training data is collected. When `battle_mode` is set to `self_play_mode` it means that the data collection occurs in a self-play setup. In other words, two identical agents play against each other to generate training data.

- If `battle_mode`  is set to `play_with_bot_mode`, it indicates that during the data collection phase, the agent plays against a predefined bot, akin to a single-player mode. In this mode, the agent plays against a fixed bot to generate training data.

- In both of these modes, when the algorithm enters the evaluation phase, `battle_mode` switches to `eval_mode`. In this mode, the agent plays against a bot to evaluate the agent's performance. This way, we can understand the degree of learning and improvement of the agent based on the outcomes of the matchups against the bot.

- Are you interested in employing the AlphaZero algorithm or similar methods from LightZero to train an effective agent within the ChessEnv environment? Or, are you simply interested in utilizing the ChessEnv environment alongside any other reinforcement learning algorithm? Which interfaces and configs need to be added in the ChessEnv environment depends on your needs. If you want to use algorithms such as AlphaZero in LightZero, we can provide a runnable demo config in about 3 weeks, but due to time constraints, good performance may not be guaranteed.
