### ISSUE TITLE
__emplace_back still causes compilation issues on m1

### ISSUE THREAD

**Issue by dan-jacobson** [opendilab/LightZero#87]
Hi y'all,

I'm running clang 14.0.3 on m1 pro, and instillation fails because of a compilation error in:
`lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp`
specifically line 384:
`disc_action_with_probs.__emplace_back(std::make_pair(iter, disturbed_probs[iter]));`

When i remove the dunder from `emplace_back` everything is happy and works fine. Working line:

`disc_action_with_probs.emplace_back(std::make_pair(iter, disturbed_probs[iter]));`

Details:
2021 M1 Pro
MacOS 13.4.1
Apple clang version 14.0.3 (clang-1403.0.22.14.1)

**Comment by puyuan1996** [comment]
Hello,

We have chosen to use `emplace_back` instead of `push_back` because it is more efficient in terms of implementation. However, in our actual implementation, we have been using `__emplace_back` due to our testing environment being macOS `clang-1316.0.21.2.3`. We plan to conduct tests on the latest version of clang, and if `emplace_back` works without any issues, we will update the installation instructions to specify the required clang version. 

Thank you very much for your advice and support.
